spring:
  application:
    name: getflix
  datasource:
    url: jdbc:sqlite:getflix.db
    driver-class-name: org.sqlite.JDBC
  #    url: jdbc:postgresql://localhost:5432/movie_db
  #    username: postgres
  #    password: postgres
  #    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      #      ddl-auto: create-drop
      ddl-auto: update
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    #    show-sql: true
    show-sql: false
    properties:
      hibernate:
        format_sql: true
