spring:
  application:
    name: getflix
  datasource:
    url: jdbc:sqlite:getflix-test.db
    driver-class-name: org.sqlite.JDBC
  #    url: jdbc:postgresql://localhost:5432/movie_db
  #    username: postgres
  #    password: postgres
  #    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    #      ddl-auto: update
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org.springframework.boot.autoconfigure.orm.jpa.JpaBaseConfiguration$JpaWebConfiguration: OFF